### PR TITLE
add local sonar analysis

### PR DESCRIPTION
**Pull request by renanfranca**
See https://github.com/jhipster/jhipster-lite-extension/issues/24

### CODE REVIEW

**Comment by renanfranca** [comment]
[The CI failure](https://github.com/jhipster/jhipster-lite-extension/actions/runs/9550127810/job/26321798201) happened because this project had fewer tests than JHipster Lite. Therefore, Sonar isn't ready when the tests finish and try to connect to it.

CI Failure Image

I could simulate this failure on my machine by executing the following script:

```bash
docker stop sonar
docker rm sonar
docker rmi sonarqube:10.5.1-community
docker compose -f src/main/docker/sonar.yml up -d
./mvnw clean verify -Dsonar.qualitygate.wait=true sonar:sonar
```

Simulation Image

I am looking for an elegant solution instead of creating a script to retry or sleep to check if Sonar is up before running the tests.

**Comment by renanfranca** [comment]
I gave up and added a sleeper 😅😎

**Comment by pascalgrimaud** [comment]
Adding a sleep is a simple solution, no need to go further, as it's enough for our use

**Comment by renanfranca** [comment]
> Adding a sleep is a simple solution, no need to go further, as it's enough for our use

Thanks for the feedback 😀

**Pull request merged**
